//! Parity tests: Rust vs Python numerical equivalence.
//!
//! Component tests use hardcoded expected values derived from the same formula.
//! JSON-driven tests load tests/vectors.json (generated by tools/gen_test_vectors.py).
//! If vectors.json is absent, JSON-driven tests are silently skipped.
//!
//! Run all:  cargo test -p needle-core
//! Run one:  cargo test -p needle-core test_zc_rms_norm

use needle_core::attn::{AttnWeights, KvCache};
use needle_core::config::TransformerConfig;
use needle_core::layers::{DecoderLayer, EncoderLayer};
use needle_core::model::NeedleModel;
use needle_core::norm::zc_rms_norm_vec;
use needle_core::quant::QuantizedWeight;
use needle_core::rope::RopeCache;

const TOL: f32 = 1e-5;

fn assert_close(got: &[f32], want: &[f32], label: &str) {
    assert_eq!(got.len(), want.len(), "{label}: length mismatch");
    for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
        let diff = (g - w).abs();
        assert!(
            diff < TOL,
            "{label}[{i}]: got {g:.8} want {w:.8} diff {diff:.2e}",
        );
    }
}

fn load_vectors() -> Option<serde_json::Value> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/vectors.json");
    let data = std::fs::read_to_string(path).ok()?;
    serde_json::from_str(&data).ok()
}

fn json_f32_vec(v: &serde_json::Value) -> Vec<f32> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|n| n.as_f64().unwrap() as f32)
        .collect()
}

/// Recursively flatten a nested JSON array of numbers into a flat Vec<f32>.
fn json_f32_flat(v: &serde_json::Value) -> Vec<f32> {
    let mut out = Vec::new();
    flatten_val(v, &mut out);
    out
}

fn flatten_val(v: &serde_json::Value, out: &mut Vec<f32>) {
    match v {
        serde_json::Value::Array(arr) => {
            for item in arr {
                flatten_val(item, out);
            }
        }
        serde_json::Value::Number(n) => out.push(n.as_f64().unwrap() as f32),
        _ => {}
    }
}

// ── ZCRMSNorm — hardcoded ────────────────────────────────────────────────────

#[test]
fn test_zc_rms_norm_zero_scale() {
    let x_in = [1.0f32, 2.0, 3.0, 4.0];
    let scale = [0.0f32; 4];

    let mean_sq: f32 = x_in.iter().map(|v| v * v).sum::<f32>() / 4.0;
    let inv = 1.0 / (mean_sq + 1e-6f32).sqrt();
    let want: Vec<f32> = x_in.iter().map(|&v| v * inv).collect();

    let mut x = x_in.to_vec();
    zc_rms_norm_vec(&mut x, &scale);
    assert_close(&x, &want, "zc_rms_norm zero_scale");
}

#[test]
fn test_zc_rms_norm_nonzero_scale() {
    let x_in = [1.0f32, 2.0, 3.0, 4.0];
    let scale = [0.1f32, -0.2, 0.3, -0.4];

    let mean_sq: f32 = x_in.iter().map(|v| v * v).sum::<f32>() / 4.0;
    let inv = 1.0 / (mean_sq + 1e-6f32).sqrt();
    let want: Vec<f32> = x_in
        .iter()
        .zip(scale.iter())
        .map(|(&v, &s)| (1.0 + s) * v * inv)
        .collect();

    let mut x = x_in.to_vec();
    zc_rms_norm_vec(&mut x, &scale);
    assert_close(&x, &want, "zc_rms_norm nonzero_scale");
}

#[test]
fn test_zc_rms_norm_eps_inside_sqrt() {
    let x_in = [1e-4f32; 4];
    let scale = [0.0f32; 4];

    let mean_sq: f32 = x_in.iter().map(|v| v * v).sum::<f32>() / 4.0;
    let inv_correct = 1.0 / (mean_sq + 1e-6f32).sqrt();
    let want: Vec<f32> = x_in.iter().map(|&v| v * inv_correct).collect();

    let mut x = x_in.to_vec();
    zc_rms_norm_vec(&mut x, &scale);
    assert_close(&x, &want, "eps_inside_sqrt");

    assert!(
        x[0] < 1.0,
        "eps must be inside sqrt — output should be ~0.1, not ~9.9"
    );
}

// ── RoPE — hardcoded ─────────────────────────────────────────────────────────

#[test]
fn test_rope_identity_at_pos0() {
    let head_dim = 4;
    let rope = RopeCache::new(8, head_dim, 10000.0);

    let orig = vec![1.0f32, 2.0, 3.0, 4.0];
    let mut q = orig.clone();
    rope.apply(&mut q, 1, 1, head_dim, 0);
    assert_close(&q, &orig, "rope_identity_pos0");
}

#[test]
fn test_rope_pos1_head_dim4() {
    let head_dim = 4;
    let rope = RopeCache::new(8, head_dim, 10000.0);

    let mut q = vec![1.0f32, 2.0, 3.0, 4.0];
    rope.apply(&mut q, 1, 1, head_dim, 1);

    let c0 = 1.0f32.cos();
    let s0 = 1.0f32.sin();
    let c1 = 0.01f32.cos();
    let s1 = 0.01f32.sin();
    let want = [
        1.0 * c0 - 3.0 * s0,
        2.0 * c1 - 4.0 * s1,
        3.0 * c0 + 1.0 * s0,
        4.0 * c1 + 2.0 * s1,
    ];
    assert_close(&q, &want, "rope_pos1_head4");
}

// ── KV cache overflow — safety ───────────────────────────────────────────────

/// KvCache must saturate at max_len without panicking.
/// Excess push_kv calls are silently ignored; len never exceeds max_len.
#[test]
fn test_kv_cache_saturates_at_max_len() {
    let max_len = 4;
    let num_kv_heads = 2;
    let head_dim = 8;
    let stride = num_kv_heads * head_dim;

    let mut cache = KvCache::new(max_len, num_kv_heads, head_dim);
    let k: Vec<f32> = (0..stride).map(|i| i as f32).collect();
    let v: Vec<f32> = (0..stride).map(|i| i as f32 * 2.0).collect();

    for _ in 0..max_len {
        cache.push_kv(&k, &v);
    }
    assert_eq!(cache.len, max_len, "cache should be full at max_len");

    // These must not panic or corrupt state
    cache.push_kv(&k, &v);
    cache.push_kv(&k, &v);
    assert_eq!(
        cache.len, max_len,
        "cache.len must not exceed max_len after overflow"
    );
}

// ── Quantization — hardcoded ─────────────────────────────────────────────────

#[test]
fn test_quant_matvec_roundtrip() {
    let w: Vec<f32> = (0..16).map(|i| (i as f32 - 7.5) * 0.9).collect();
    let qw = QuantizedWeight::quantize(&w, 4, 4);

    let x = vec![1.0f32, 0.0, 0.0, 0.0];
    let mut y = vec![0.0f32; 4];
    qw.matvec(&x, &mut y);

    let mut dq = vec![0.0f32; 16];
    qw.dequantize_to(&mut dq);
    let expected = &dq[0..4];

    assert_close(&y, expected, "quant_matvec_roundtrip");
}

// ── JSON-driven component parity (skipped if vectors.json absent) ─────────────

#[test]
fn test_json_zc_rms_norm() {
    let Some(v) = load_vectors() else { return };

    let x_in = json_f32_vec(&v["zc_rms_norm"]["x"]);
    let scale_zero = json_f32_vec(&v["zc_rms_norm"]["scale_zero"]);
    let want_zero = json_f32_vec(&v["zc_rms_norm"]["out_zero"]);
    let scale_nz = json_f32_vec(&v["zc_rms_norm"]["scale_nonzero"]);
    let want_nz = json_f32_vec(&v["zc_rms_norm"]["out_nonzero"]);

    let mut x = x_in.clone();
    zc_rms_norm_vec(&mut x, &scale_zero);
    assert_close(&x, &want_zero, "json_zc_zero");

    let mut x2 = x_in.clone();
    zc_rms_norm_vec(&mut x2, &scale_nz);
    assert_close(&x2, &want_nz, "json_zc_nonzero");
}

#[test]
fn test_json_rope() {
    let Some(v) = load_vectors() else { return };

    let head_dim = v["rope"]["head_dim"].as_u64().unwrap() as usize;
    let rope = RopeCache::new(8, head_dim, 10000.0);

    let q_before = json_f32_vec(&v["rope"]["q_before"]);
    let want_pos0 = json_f32_vec(&v["rope"]["q_after_pos0"]);

    let mut q = q_before.clone();
    rope.apply(&mut q, 1, 1, head_dim, 0);
    assert_close(&q, &want_pos0, "json_rope_pos0");
}

#[test]
fn test_json_quantization() {
    let Some(v) = load_vectors() else { return };

    let shape = v["quantization"]["w_shape"].as_array().unwrap();
    let in_feat = shape[0].as_u64().unwrap() as usize;
    let out_feat = shape[1].as_u64().unwrap() as usize;

    let w = json_f32_flat(&v["quantization"]["w"]);
    let want_scales = json_f32_flat(&v["quantization"]["scales"]);

    let qw = QuantizedWeight::quantize(&w, in_feat, out_feat);

    let scale_tol = 1e-6f32;
    assert_eq!(qw.scales.len(), want_scales.len(), "scales length");
    for (i, (got, want)) in qw.scales.iter().zip(want_scales.iter()).enumerate() {
        assert!(
            (got - want).abs() < scale_tol,
            "scale[{i}]: got {got} want {want}"
        );
    }
}

// ── Full model forward parity ─────────────────────────────────────────────────

/// Build NeedleModel from test vectors JSON.
/// Attention weights are stored as f32 and quantized to INT4 here.
fn model_from_json(v: &serde_json::Value) -> NeedleModel {
    let d = v["config"]["d_model"].as_u64().unwrap() as usize;
    let h = v["config"]["num_heads"].as_u64().unwrap() as usize;
    let kv_h = v["config"]["num_kv_heads"].as_u64().unwrap() as usize;
    let vocab_size = v["config"]["vocab_size"].as_u64().unwrap() as usize;
    let num_enc = v["config"]["num_encoder_layers"].as_u64().unwrap() as usize;
    let num_dec = v["config"]["num_decoder_layers"].as_u64().unwrap() as usize;
    let hd = d / h;
    let q_dim = h * hd; // = d_model for our config
    let kv_dim = kv_h * hd;

    let cfg = TransformerConfig {
        d_model: d,
        num_heads: h,
        num_kv_heads: kv_h,
        vocab_size,
        num_layers: num_enc,
        num_dec_layers: num_dec,
        max_enc_len: 16,
        max_dec_len: 16,
        ..TransformerConfig::default()
    };

    let w = &v["weights"];

    let embedding = json_f32_flat(&w["embedding"]);
    let encoder_final_norm = json_f32_vec(&w["encoder_final_norm"]);
    let decoder_final_norm = json_f32_vec(&w["decoder_final_norm"]);

    fn load_attn(sa: &serde_json::Value, d: usize, q_dim: usize, kv_dim: usize) -> AttnWeights {
        AttnWeights {
            wq: QuantizedWeight::quantize(&json_f32_flat(&sa["q_proj"]), d, q_dim),
            wk: QuantizedWeight::quantize(&json_f32_flat(&sa["k_proj"]), d, kv_dim),
            wv: QuantizedWeight::quantize(&json_f32_flat(&sa["v_proj"]), d, kv_dim),
            wo: QuantizedWeight::quantize(&json_f32_flat(&sa["out_proj"]), d, d),
            q_norm: json_f32_vec(&sa["q_norm"]),
            k_norm: json_f32_vec(&sa["k_norm"]),
        }
    }

    let encoder_layers: Vec<EncoderLayer> = w["encoder_layers"]
        .as_array()
        .unwrap()
        .iter()
        .map(|l| EncoderLayer {
            self_attn: load_attn(&l["self_attn"], d, q_dim, kv_dim),
            self_attn_gate: l["self_attn_gate"].as_f64().unwrap() as f32,
            norm: json_f32_vec(&l["norm"]),
            ffn: None,
            ffn_gate: 0.0,
            ffn_norm: None,
            ffn_activation: None,
        })
        .collect();

    let decoder_layers: Vec<DecoderLayer> = w["decoder_layers"]
        .as_array()
        .unwrap()
        .iter()
        .map(|l| DecoderLayer {
            self_attn: load_attn(&l["self_attn"], d, q_dim, kv_dim),
            self_attn_gate: l["self_attn_gate"].as_f64().unwrap() as f32,
            self_attn_norm: json_f32_vec(&l["self_attn_norm"]),
            cross_attn: load_attn(&l["cross_attn"], d, q_dim, kv_dim),
            cross_attn_gate: l["cross_attn_gate"].as_f64().unwrap() as f32,
            cross_attn_norm: json_f32_vec(&l["cross_attn_norm"]),
            ffn: None,
            ffn_gate: 0.0,
            ffn_norm: None,
            ffn_activation: None,
        })
        .collect();

    NeedleModel::new(
        cfg,
        embedding,
        encoder_layers,
        decoder_layers,
        encoder_final_norm,
        decoder_final_norm,
    )
}

#[test]
fn test_full_forward_pred_token() {
    let Some(v) = load_vectors() else { return };

    let want_pred = v["forward"]["pred_token"].as_u64().unwrap() as u32;
    let enc_ids: Vec<u32> = v["inputs"]["enc_ids"]
        .as_array()
        .unwrap()
        .iter()
        .map(|n| n.as_u64().unwrap() as u32)
        .collect();
    let dec_start = v["inputs"]["dec_start_id"].as_u64().unwrap() as u32;

    let model = model_from_json(&v);
    let enc_len = enc_ids.len();
    let vocab = model.cfg.vocab_size;

    let mut enc_kv = model.make_enc_kv_caches(enc_len);
    let mut dec_kv = model.make_dec_kv_caches();

    model.encode(&enc_ids, &mut enc_kv);

    let mut logits = vec![0.0f32; vocab];
    model.decode_step(dec_start, &enc_kv, &mut dec_kv, &mut logits);

    let got_pred = logits
        .iter()
        .enumerate()
        .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
        .map(|(i, _)| i as u32)
        .unwrap();

    // The Python model uses f32 weights; Rust uses INT4-quantized weights.
    // Quantization introduces small error (~0.01 per layer). We check that
    // the argmax (pred_token) agrees — the margin between top-2 logits is
    // recorded so we can diagnose close misses.
    let sorted_logits = {
        let mut v: Vec<(usize, f32)> = logits.iter().cloned().enumerate().collect();
        v.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        v
    };
    let margin = sorted_logits[0].1 - sorted_logits[1].1;

    assert_eq!(
        got_pred, want_pred,
        "pred_token mismatch: Rust={got_pred} Python={want_pred} \
         (top logit {:.4}, margin {margin:.4})",
        sorted_logits[0].1
    );
}

/// Exact parity: Rust INT4 vs Python INT4 (fake-quantized) forward pass.
/// pred_token_q is computed in Python with the same INT4-fake-quantized kernels
/// that Rust uses, so the argmax MUST match exactly (margin >> rounding error).
#[test]
fn test_full_forward_pred_token_exact() {
    let Some(v) = load_vectors() else { return };
    let Some(ptq) = v["forward"].get("pred_token_q") else {
        return;
    };
    let want_pred = ptq.as_u64().unwrap() as u32;

    let enc_ids: Vec<u32> = v["inputs"]["enc_ids"]
        .as_array()
        .unwrap()
        .iter()
        .map(|n| n.as_u64().unwrap() as u32)
        .collect();
    let dec_start = v["inputs"]["dec_start_id"].as_u64().unwrap() as u32;

    let model = model_from_json(&v);
    let enc_len = enc_ids.len();
    let vocab = model.cfg.vocab_size;

    let mut enc_kv = model.make_enc_kv_caches(enc_len);
    let mut dec_kv = model.make_dec_kv_caches();
    model.encode(&enc_ids, &mut enc_kv);

    let mut logits = vec![0.0f32; vocab];
    model.decode_step(dec_start, &enc_kv, &mut dec_kv, &mut logits);

    let got_pred = logits
        .iter()
        .enumerate()
        .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
        .map(|(i, _)| i as u32)
        .unwrap();

    assert_eq!(
        got_pred, want_pred,
        "Rust INT4 pred={got_pred} vs Python INT4 pred_token_q={want_pred} — must be exact"
    );
}

/// Check Rust INT4 logits vs Python-INT4-fake-quantized logits.
/// Any remaining diff is purely FP accumulation order (not quantization).
/// Tolerance 0.05 is generous relative to the ~0.2 logit margin on this model.
#[test]
fn test_full_forward_logits_quant_close() {
    let Some(v) = load_vectors() else { return };
    let Some(lq) = v["forward"].get("logits_q") else {
        return;
    };

    let want_logits = json_f32_vec(lq);
    let enc_ids: Vec<u32> = v["inputs"]["enc_ids"]
        .as_array()
        .unwrap()
        .iter()
        .map(|n| n.as_u64().unwrap() as u32)
        .collect();
    let dec_start = v["inputs"]["dec_start_id"].as_u64().unwrap() as u32;

    let model = model_from_json(&v);
    let enc_len = enc_ids.len();
    let vocab = model.cfg.vocab_size;

    let mut enc_kv = model.make_enc_kv_caches(enc_len);
    let mut dec_kv = model.make_dec_kv_caches();
    model.encode(&enc_ids, &mut enc_kv);

    let mut got_logits = vec![0.0f32; vocab];
    model.decode_step(dec_start, &enc_kv, &mut dec_kv, &mut got_logits);

    // Accumulation-order diff only — expect << 0.05 for d=16 chains
    let tol = 0.05f32;
    let mut max_diff = 0.0f32;
    for (i, (got, want)) in got_logits.iter().zip(want_logits.iter()).enumerate() {
        let diff = (got - want).abs();
        if diff > max_diff {
            max_diff = diff;
        }
        assert!(
            diff < tol,
            "logit_q[{i}]: Rust={got:.6} Python-INT4={want:.6} diff={diff:.6} > {tol}"
        );
    }
    eprintln!("max logit diff (Rust vs Python-INT4): {max_diff:.6}");
}

/// Encoder hidden-state parity: Rust INT4 encoder output vs Python INT4-fakeq encoder output.
/// Both use the same INT4-quantized attention kernels, so FP accumulation order is the only diff.
/// Tolerance 0.05 is generous relative to the scale of typical hidden values (~1.0–5.0).
#[test]
fn test_encoder_hidden_parity() {
    let Some(v) = load_vectors() else { return };
    let Some(eq) = v["forward"].get("enc_out_q") else {
        return;
    };

    let want: Vec<f32> = json_f32_flat(eq);
    let enc_ids: Vec<u32> = v["inputs"]["enc_ids"]
        .as_array()
        .unwrap()
        .iter()
        .map(|n| n.as_u64().unwrap() as u32)
        .collect();

    let model = model_from_json(&v);
    let enc_len = enc_ids.len();

    let mut enc_kv = model.make_enc_kv_caches(enc_len);
    let got = model.encode(&enc_ids, &mut enc_kv);

    assert_eq!(got.len(), want.len(), "encoder hidden shape mismatch");
    let tol = 0.05f32;
    let mut max_diff = 0.0f32;
    for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
        let diff = (g - w).abs();
        if diff > max_diff {
            max_diff = diff;
        }
        assert!(
            diff < tol,
            "enc_out_q[{i}]: Rust={g:.6} Python={w:.6} diff={diff:.6} > tol={tol}"
        );
    }
    eprintln!("encoder hidden parity max diff: {max_diff:.6}");
}

/// Multi-step decode parity: Rust incremental KV-cache decode vs Python full-prefix decode.
/// Python re-encodes the full prefix each step (no cache); Rust extends the KV cache.
/// If they agree, the Rust KV cache is correct. Assertion is:
///   - strict (exact token match) when Python's top-1/top-2 margin > 0.05
///   - relaxed (Rust token in Python's top-2) when margin is tight
#[test]
fn test_multi_step_decode_parity() {
    let Some(v) = load_vectors() else { return };
    let Some(ms) = v.get("multi_step") else {
        return;
    };

    let enc_ids: Vec<u32> = v["inputs"]["enc_ids"]
        .as_array()
        .unwrap()
        .iter()
        .map(|n| n.as_u64().unwrap() as u32)
        .collect();
    let dec_start = v["inputs"]["dec_start_id"].as_u64().unwrap() as u32;

    let model = model_from_json(&v);
    let enc_len = enc_ids.len();
    let vocab = model.cfg.vocab_size;

    let mut enc_kv = model.make_enc_kv_caches(enc_len);
    let mut dec_kv = model.make_dec_kv_caches();
    model.encode(&enc_ids, &mut enc_kv);

    let steps = ms["steps"].as_array().unwrap();
    let mut current_token = dec_start;

    for (step_i, step) in steps.iter().enumerate() {
        let want_pred = step["pred_token"].as_u64().unwrap() as u32;
        let margin = step["margin"].as_f64().unwrap() as f32;
        let top5: Vec<u32> = step["top5_tokens"]
            .as_array()
            .unwrap()
            .iter()
            .map(|n| n.as_u64().unwrap() as u32)
            .collect();

        let mut logits = vec![0.0f32; vocab];
        model.decode_step(current_token, &enc_kv, &mut dec_kv, &mut logits);

        let got_pred = logits
            .iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .map(|(i, _)| i as u32)
            .unwrap();

        if margin > 0.05 {
            assert_eq!(
                got_pred, want_pred,
                "step {step_i}: Rust pred={got_pred} Python pred={want_pred} margin={margin:.4}"
            );
        } else {
            assert!(
                top5.contains(&got_pred),
                "step {step_i}: Rust pred={got_pred} not in Python top-5={top5:?} (tight margin={margin:.4})"
            );
        }

        eprintln!("step {step_i}: input={current_token} Rust={got_pred} Python={want_pred} margin={margin:.4}");
        current_token = got_pred;
    }
}

/// Verify Python f32 logits vs Rust INT4 logits are within INT4 quantization tolerance.
/// This is a softer check that confirms the architecture is correct even if pred_token
/// happens to differ at the boundary.
#[test]
fn test_full_forward_logits_close() {
    let Some(v) = load_vectors() else { return };

    let want_logits = json_f32_vec(&v["forward"]["logits"]);
    let enc_ids: Vec<u32> = v["inputs"]["enc_ids"]
        .as_array()
        .unwrap()
        .iter()
        .map(|n| n.as_u64().unwrap() as u32)
        .collect();
    let dec_start = v["inputs"]["dec_start_id"].as_u64().unwrap() as u32;

    let model = model_from_json(&v);
    let enc_len = enc_ids.len();
    let vocab = model.cfg.vocab_size;

    let mut enc_kv = model.make_enc_kv_caches(enc_len);
    let mut dec_kv = model.make_dec_kv_caches();

    model.encode(&enc_ids, &mut enc_kv);

    let mut got_logits = vec![0.0f32; vocab];
    model.decode_step(dec_start, &enc_kv, &mut dec_kv, &mut got_logits);

    // INT4 quantization error tolerance: with d=16 and scale≈0.02/14,
    // accumulated across 5 sub-layers, expect max error < 1.0 per logit.
    let int4_tol = 1.0f32;
    let mut max_diff = 0.0f32;
    for (i, (got, want)) in got_logits.iter().zip(want_logits.iter()).enumerate() {
        let diff = (got - want).abs();
        if diff > max_diff {
            max_diff = diff;
        }
        assert!(
            diff < int4_tol,
            "logit[{i}]: Rust={got:.6} Python={want:.6} diff={diff:.4} > tol={int4_tol}"
        );
    }
    eprintln!("max logit diff (Rust INT4 vs Python f32): {max_diff:.6}");
}

/// Non-power-of-2 in_feat: quantize pads to the next GROUP_SIZE multiple.
/// Verifies that matvec matches dequantize+naive-dot for in_feat=33 (→64) and in_feat=65 (→96).
#[test]
fn test_quant_nonaligned_infeats() {
    for &(in_feat, out_feat) in &[(33usize, 8usize), (65, 16)] {
        let w: Vec<f32> = (0..in_feat * out_feat)
            .map(|i| (i as f32) * 0.13 - 4.0)
            .collect();

        let qw = QuantizedWeight::quantize(&w, in_feat, out_feat);

        // Dequantize to f32 and check matvec matches naive dot
        let mut dq = vec![0.0f32; in_feat * out_feat];
        qw.dequantize_to(&mut dq);

        let x: Vec<f32> = (0..in_feat).map(|i| ((i as f32) * 0.1).sin()).collect();

        let mut y_ref = vec![0.0f32; out_feat];
        for o in 0..out_feat {
            for i in 0..in_feat {
                y_ref[o] += x[i] * dq[i * out_feat + o];
            }
        }

        let mut y_got = vec![0.0f32; out_feat];
        qw.matvec(&x, &mut y_got);

        for o in 0..out_feat {
            let diff = (y_got[o] - y_ref[o]).abs();
            let tol = 1e-3 * y_ref[o].abs().max(1.0);
            assert!(
                diff < tol,
                "in_feat={in_feat} matvec[{o}]: got={:.6} ref={:.6} diff={diff:.6} tol={tol:.6}",
                y_got[o],
                y_ref[o]
            );
        }
        eprintln!("nonaligned in_feat={in_feat} out_feat={out_feat}: OK");
    }
}

#[test]
fn test_config_validate_rejects_bad_head_divisibility() {
    let mut cfg = TransformerConfig::default();
    // Default is valid
    assert!(cfg.validate().is_ok(), "default config must be valid");

    // d_model not divisible by num_heads → silent wrong head_dim
    cfg.d_model = 513; // 513 % 8 != 0
    assert!(
        cfg.validate().is_err(),
        "d_model=513, num_heads=8 must fail"
    );

    // num_heads not divisible by num_kv_heads
    cfg.d_model = 512;
    cfg.num_kv_heads = 3; // 8 % 3 != 0
    assert!(
        cfg.validate().is_err(),
        "num_heads=8, num_kv_heads=3 must fail"
    );

    assert!(
        TransformerConfig {
            num_heads: 0,
            ..Default::default()
        }
        .validate()
        .is_err(),
        "num_heads=0 must fail"
    );
    assert!(
        TransformerConfig {
            vocab_size: 0,
            ..Default::default()
        }
        .validate()
        .is_err(),
        "vocab_size=0 must fail"
    );
}
