//! End-to-end parity tests: Rust engine.run() vs Python reference (tools/gen_e2e_vectors.py).
//!
//! Verifies that the complete Rust pipeline — tokenize → INT4-quantized encode →
//! constrained greedy decode — produces the same token sequence and output text as
//! the Python reference implementation.
//!
//! Requires:
//!   weights/needle.safetensors  — generated by tools/export.py
//!   weights/vocab.txt           — generated by tools/export.py
//!   tests/e2e_vectors.json      — generated by tools/gen_e2e_vectors.py
//!
//! Run: cargo test -p needle-infer e2e -- --nocapture

use needle_infer::engine::NeedleEngine;

const WEIGHTS: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../weights/needle.safetensors"
);
const VOCAB: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../weights/vocab.txt");
const E2E_VECTORS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/e2e_vectors.json");

fn files_available() -> bool {
    std::path::Path::new(WEIGHTS).exists()
        && std::path::Path::new(VOCAB).exists()
        && std::path::Path::new(E2E_VECTORS).exists()
}

fn load_engine() -> NeedleEngine {
    NeedleEngine::load(WEIGHTS, VOCAB).expect("engine load failed")
}

fn load_vectors() -> serde_json::Value {
    let data = std::fs::read_to_string(E2E_VECTORS).expect("e2e_vectors.json read failed");
    serde_json::from_str(&data).expect("e2e_vectors.json parse failed")
}

/// Loose text normalisation for comparison: collapse whitespace, lower case.
fn normalise(s: &str) -> String {
    s.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .to_lowercase()
}

/// Full pipeline parity: token IDs and decoded text must match Python exactly.
///
/// Token IDs are produced by deterministic greedy argmax with the same INT4
/// quantized weights and constrained decoder, so any deviation indicates a
/// bug in the Rust tokenizer, engine, or constrained decoder.
#[test]
fn test_e2e_token_and_text_parity() {
    if !files_available() {
        eprintln!("SKIP: {E2E_VECTORS}, {WEIGHTS}, or {VOCAB} not found");
        return;
    }

    let engine = load_engine();
    let vectors = load_vectors();
    let examples = vectors["examples"].as_array().expect("examples array");

    let mut all_passed = true;

    for (i, ex) in examples.iter().enumerate() {
        let query = ex["query"].as_str().unwrap();
        let tools = ex["tools"].as_str().unwrap();
        let want_tokens: Vec<u32> = ex["expected_token_ids"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        let want_text = ex["expected_text"].as_str().unwrap();

        let result = engine.run(query, tools);

        let tok_match = result.token_ids == want_tokens;
        let text_match = normalise(&result.text) == normalise(want_text);

        eprintln!("\nExample {i}: query={query:?}");
        eprintln!(
            "  Rust  tokens ({:>3}): {:?}",
            result.token_ids.len(),
            &result.token_ids[..result.token_ids.len().min(10)]
        );
        eprintln!(
            "  Python tokens ({:>3}): {:?}",
            want_tokens.len(),
            &want_tokens[..want_tokens.len().min(10)]
        );
        eprintln!("  Rust  text: {:?}", result.text);
        eprintln!("  Python text: {:?}", want_text);
        eprintln!("  tokens_match={tok_match}  text_match={text_match}");

        if !tok_match {
            // Advisory: token mismatch in unconstrained value regions is acceptable
            // (floating-point rounding can pick different tokens that decode identically).
            let first_diff = result
                .token_ids
                .iter()
                .zip(want_tokens.iter())
                .enumerate()
                .find(|(_, (r, p))| r != p);
            if let Some((pos, (r, p))) = first_diff {
                eprintln!(
                    "  INFO: first token divergence at step {pos}: Rust={r} Python={p} \
                           (acceptable if in unconstrained value region)"
                );
            } else {
                eprintln!(
                    "  INFO: token length mismatch: Rust={} Python={} \
                           (acceptable if text matches)",
                    result.token_ids.len(),
                    want_tokens.len()
                );
            }
        }

        // Text match is the primary criterion for production correctness.
        if !text_match {
            eprintln!("  FAIL: text mismatch");
            all_passed = false;
        }
    }

    assert!(all_passed, "e2e parity failed — see stderr for details");
}

/// Semantic sanity check: output is valid JSON with expected tool name and argument keys.
/// Runs even without e2e_vectors.json (only needs weights + vocab).
#[test]
fn test_e2e_semantic_correctness() {
    if !std::path::Path::new(WEIGHTS).exists() || !std::path::Path::new(VOCAB).exists() {
        eprintln!("SKIP: weights not found");
        return;
    }

    let engine = load_engine();

    let cases: &[(&str, &str, &str, &[&str])] = &[
        (
            "What's the weather in Paris?",
            r#"[{"name":"get_weather","description":"Get weather","parameters":{"location":{"type":"string"},"unit":{"type":"string"}}}]"#,
            "get_weather",
            &["location"],
        ),
        (
            "Search for Python tutorials",
            r#"[{"name":"web_search","description":"Search","parameters":{"query":{"type":"string"}}}]"#,
            "web_search",
            &["query"],
        ),
    ];

    for (query, tools, expected_name, expected_keys) in cases {
        let result = engine.run(query, tools);
        eprintln!("\nQuery: {query:?}");
        eprintln!("Output: {:?}", result.text);

        // Text should mention the expected tool name
        assert!(
            result.text.contains(expected_name),
            "query={query:?}: expected tool {expected_name:?} in output, got {:?}",
            result.text
        );

        // All expected argument keys should appear
        for key in *expected_keys {
            assert!(
                result.text.contains(key),
                "query={query:?}: expected arg key {key:?} in output, got {:?}",
                result.text
            );
        }

        // Output should be parseable JSON. The <tool_call> prefix is now stripped
        // by engine.run() to match Python's generate() contract.
        let json_part = result.text.trim();
        if !json_part.is_empty() {
            assert!(
                !json_part.starts_with("<tool_call>"),
                "query={query:?}: <tool_call> prefix not stripped — Python contract violated"
            );
            serde_json::from_str::<serde_json::Value>(json_part).unwrap_or_else(|e| {
                panic!("query={query:?}: output is not valid JSON: {e}\n  output={json_part:?}")
            });
        }
    }
}
