//! Real-model parity tests: Rust engine vs Python reference (tools/gen_real_vectors.py).
//!
//! Requires:
//!   weights/needle.safetensors  — generated by tools/export.py
//!   tests/real_vectors.json     — generated by tools/gen_real_vectors.py
//!
//! Uses model.encode() + model.decode_step() directly to bypass the constrained
//! decoder stub and test the raw model numerics.
//!
//! Run: cargo test -p needle-infer real_parity -- --nocapture

use needle_infer::engine::NeedleEngine;

const WEIGHTS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../weights/needle.safetensors");
const REAL_VECTORS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/real_vectors.json");

fn files_available() -> bool {
    std::path::Path::new(WEIGHTS).exists() && std::path::Path::new(REAL_VECTORS).exists()
}

fn load_vectors() -> Option<serde_json::Value> {
    let data = std::fs::read_to_string(REAL_VECTORS).ok()?;
    serde_json::from_str(&data).ok()
}

fn json_f32_flat(v: &serde_json::Value) -> Vec<f32> {
    let mut out = Vec::new();
    flatten(v, &mut out);
    out
}

fn flatten(v: &serde_json::Value, out: &mut Vec<f32>) {
    match v {
        serde_json::Value::Array(arr) => arr.iter().for_each(|x| flatten(x, out)),
        serde_json::Value::Number(n) => out.push(n.as_f64().unwrap() as f32),
        _ => {}
    }
}

/// Load the real model and a dummy vocab path (vocab is not needed for this test).
fn load_engine() -> NeedleEngine {
    let vocab = concat!(env!("CARGO_MANIFEST_DIR"), "/../../weights/vocab.txt");
    NeedleEngine::load(WEIGHTS, vocab).expect("engine load failed")
}

/// Encoder hidden-state parity with real 26M weights.
/// Both Rust and Python apply identical INT4 fake-quantization, so FP order is the only diff.
#[test]
fn test_real_encoder_hidden_parity() {
    if !files_available() {
        eprintln!("SKIP: {} or {} not found", WEIGHTS, REAL_VECTORS);
        return;
    }

    let v = load_vectors().expect("real_vectors.json parse failed");
    let enc_ids: Vec<u32> = v["enc_ids"].as_array().unwrap().iter()
        .map(|n| n.as_u64().unwrap() as u32)
        .collect();
    let want_enc: Vec<f32> = json_f32_flat(&v["enc_out_q"]);

    let engine = load_engine();
    let model = engine.model();
    let enc_len = enc_ids.len();
    let mut enc_kv = model.make_enc_kv_caches(enc_len);
    let got_enc = model.encode(&enc_ids, &mut enc_kv);

    assert_eq!(got_enc.len(), want_enc.len(), "encoder hidden length mismatch");

    let tol = 1.0f32; // real model: d=512, 12 enc layers — more INT4 error accumulation
    let mut max_diff = 0.0f32;
    let mut n_outliers = 0usize;
    for (i, (g, w)) in got_enc.iter().zip(want_enc.iter()).enumerate() {
        let diff = (g - w).abs();
        if diff > max_diff { max_diff = diff; }
        if diff > tol {
            n_outliers += 1;
            if n_outliers <= 5 {
                eprintln!("enc_out_q[{i}]: Rust={g:.4} Python={w:.4} diff={diff:.4}");
            }
        }
    }
    assert!(
        n_outliers == 0,
        "encoder parity: {n_outliers} elements exceed tol={tol}, max_diff={max_diff:.4}"
    );
    eprintln!("real encoder hidden parity: max_diff={max_diff:.4} over {} elements", got_enc.len());
}

/// Multi-step decode parity with real 26M weights.
/// Runs up to `num_steps` greedy decode iterations using Rust KV-cache and
/// compares each predicted token against Python's reference.
///
/// - margin > 0.1: strict exact-match assertion
/// - margin 0.02–0.1: Rust token must be in Python's top-2
/// - margin < 0.02: any match in Python's top-5 is acceptable (too close to call)
#[test]
fn test_real_multi_step_decode_parity() {
    if !files_available() {
        eprintln!("SKIP: {} or {} not found", WEIGHTS, REAL_VECTORS);
        return;
    }

    let v = load_vectors().expect("real_vectors.json parse failed");
    let enc_ids: Vec<u32> = v["enc_ids"].as_array().unwrap().iter()
        .map(|n| n.as_u64().unwrap() as u32)
        .collect();
    let dec_start = v["dec_start"].as_u64().unwrap() as u32;
    let steps = v["steps"].as_array().unwrap();

    let engine = load_engine();
    let model = engine.model();
    let enc_len = enc_ids.len();
    let vocab = model.cfg.vocab_size;

    let mut enc_kv = model.make_enc_kv_caches(enc_len);
    let mut dec_kv = model.make_dec_kv_caches();
    model.encode(&enc_ids, &mut enc_kv);

    let mut current_token = dec_start;
    let mut all_passed = true;

    for (step_i, step) in steps.iter().enumerate() {
        let want_pred = step["pred_token"].as_u64().unwrap() as u32;
        let margin = step["margin"].as_f64().unwrap() as f32;
        let top5: Vec<u32> = step["top5_tokens"].as_array().unwrap().iter()
            .map(|n| n.as_u64().unwrap() as u32)
            .collect();

        let mut logits = vec![0.0f32; vocab];
        model.decode_step(current_token, &enc_kv, &mut dec_kv, &mut logits);

        let got_pred = logits.iter().enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .map(|(i, _)| i as u32)
            .unwrap_or(0);

        let status = if got_pred == want_pred {
            "MATCH"
        } else if top5.contains(&got_pred) {
            "TOP5"
        } else {
            "MISS"
        };

        eprintln!("step {step_i}: input={current_token} Rust={got_pred} Python={want_pred} \
                   margin={margin:.4} [{status}]");

        if margin > 0.1 {
            if got_pred != want_pred {
                all_passed = false;
                eprintln!("  FAIL: strict mismatch (margin={margin:.4} > 0.1)");
            }
        } else if margin > 0.02 {
            if !top5[..2].contains(&got_pred) {
                all_passed = false;
                eprintln!("  FAIL: not in top-2 (margin={margin:.4})");
            }
        } else {
            if !top5.contains(&got_pred) {
                all_passed = false;
                eprintln!("  FAIL: not in top-5 (very tight margin={margin:.4})");
            }
        }

        current_token = got_pred;
    }

    assert!(all_passed, "real model multi-step decode parity failed — see stderr for details");
}
