//! Containers that `needle build --layers N` emits — the ladder's rungs.
//!
//! Needle 3 is a laddered model: every depth from 2 to 20 blocks is a trained,
//! deployable subnetwork. Upstream distributes a rung by *rewriting the
//! container* — `rung()` applies `ladder_slice` + `ladder_config`, and the
//! export writes `num_layers = N` with remapped global-attention and Engram
//! layers. Nothing in the file records that it was sliced.
//!
//! So a rung is, to us, an ordinary v3 container with a different geometry.
//! This asserts that claim across every depth the ladder defines, rather than
//! trusting it: a synthetic container is assembled for each rung's shape and
//! walked with the real `V3Layout::derive`.
//!
//! The rung geometry itself is not computed here. `tests/v3_ladder_rungs.json`
//! is generated by running upstream's own `ladder_layer_indices`, so the block
//! subsets, the remapped global layers and the remapped Engram sites are
//! upstream's answers, not ours. Deriving them independently would risk
//! agreeing with a bug in our own reimplementation.
//!
//! Run: cargo test -p needle-infer --release --test v3_rung_containers -- --nocapture

use needle_infer::cact::CactV3;
use needle_infer::v3::{config_from_geometry, V3Layout};

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tests/v3_ladder_rungs.json"
);

// A small but shape-faithful geometry: what matters for a rung is the layer
// count, the number of Engram sites and which blocks are global, all of which
// vary per depth. The widths are kept small so the file stays in memory.
const D: usize = 8;
const HEADS: usize = 2;
const KV_HEADS: usize = 1;
const QK: usize = 4;
const VH: usize = 2;
const LANES: usize = 2;
const HADA_N: usize = 8;
const VOCAB: usize = 6;
const SLOTS: usize = 16;
const TABLES: usize = 2;
const SUB_DIM: usize = 4;
const ENGRAM_TAPS: usize = 4;
const TAPS: usize = 3;
const PROBES: usize = 2;
const QUERIES: usize = 2;

struct T {
    dtype: u8,
    shape: Vec<usize>,
    blob: Vec<u8>,
}

fn fp16(shape: &[usize]) -> T {
    let n: usize = shape.iter().product::<usize>().max(1);
    T {
        dtype: 1,
        shape: shape.to_vec(),
        blob: vec![0u8; n * 2],
    }
}

fn fp16_values(shape: &[usize], values: &[f32]) -> T {
    let mut blob = Vec::new();
    for v in values {
        // Only small exact integers are needed here (head codes).
        let bits = half_bits(*v);
        blob.extend_from_slice(&bits.to_le_bytes());
    }
    T {
        dtype: 1,
        shape: shape.to_vec(),
        blob,
    }
}

fn half_bits(v: f32) -> u16 {
    let b = v.to_bits();
    let sign = ((b >> 16) & 0x8000) as u16;
    let exp = ((b >> 23) & 0xFF) as i32 - 127 + 15;
    let mant = (b & 0x007F_FFFF) >> 13;
    if v == 0.0 {
        return sign;
    }
    sign | ((exp as u16) << 10) | mant as u16
}

fn fp32_indices(n: usize) -> T {
    let mut blob = Vec::new();
    for i in 0..n {
        blob.extend_from_slice(&(i as f32).to_le_bytes());
    }
    T {
        dtype: 2,
        shape: vec![n],
        blob,
    }
}

fn raw(bytes: &[u8]) -> T {
    T {
        dtype: 4,
        shape: vec![],
        blob: bytes.to_vec(),
    }
}

fn layer_tensors(out: &mut Vec<T>) {
    let (ba, bb) = (2usize, 4usize);
    out.push(fp16(&[D]));
    out.push(fp16(&[HEADS * QK, D]));
    out.push(fp16(&[KV_HEADS * QK, D]));
    out.push(fp16(&[KV_HEADS * VH, D]));
    out.push(fp16(&[TAPS, HEADS * QK]));
    out.push(fp16(&[TAPS, KV_HEADS * QK]));
    out.push(fp16(&[TAPS, KV_HEADS * VH]));
    out.push(fp16(&[QK]));
    out.push(fp16(&[QK]));
    out.push(fp16(&[HEADS * VH, D]));
    out.push(fp16(&[D, HEADS * VH]));
    out.push(fp16(&[D]));
    out.push(fp16(&[1]));
    out.push(fp16(&[D]));
    for _ in 0..5 {
        out.push(fp16(&[HADA_N]));
    }
    for _ in 0..3 {
        out.push(fp16(&[ba, ba]));
        out.push(fp16(&[bb, bb]));
    }
    out.push(fp16(&[D, 2]));
    out.push(fp16(&[2, HADA_N]));
}

/// A container shaped exactly as `needle build --layers depth` would emit it.
fn build_rung(depth: usize, sites: &[usize], gmask: u64) -> Vec<u8> {
    const HEADER: usize = 49 * 4;
    const REC: usize = 44;
    let cb_len = needle_core::cq::CODEBOOK_LEN;

    let mut ts = vec![fp16(&[VOCAB, D])];
    for _ in 0..depth {
        layer_tensors(&mut ts);
    }
    ts.push(fp16(&[depth]));
    ts.push(fp16(&[depth]));
    ts.push(fp16(&[depth]));
    ts.push(fp16(&[depth, LANES]));
    ts.push(fp16(&[depth, LANES]));
    ts.push(fp16(&[depth, LANES, LANES]));
    ts.push(fp16(&[depth * LANES, LANES * D]));
    ts.push(fp16(&[depth * LANES, LANES * D]));
    ts.push(fp16(&[depth * LANES * LANES, LANES * D]));
    ts.push(fp32_indices(HADA_N));
    ts.push(fp32_indices(HADA_N));
    // One Engram block per surviving site — `ladder_slice` keeps whole tables
    // for kept sites and renumbers them contiguously.
    for _ in sites {
        ts.push(fp16(&[TABLES * SLOTS, SUB_DIM]));
        ts.push(fp16(&[D, TABLES * SUB_DIM]));
        ts.push(fp16(&[D, TABLES * SUB_DIM]));
        ts.push(fp16(&[ENGRAM_TAPS, D]));
    }
    ts.push(fp16(&[D])); // final_norm
                         // The confidence head keeps one cell per surviving block plus the input
                         // embedding cell — `rows = (0, *(layer + 1 for layer in selected))`.
    let rows = depth + 1;
    ts.push(fp16_values(&[1], &[2.0])); // heads.manifest: confidence
    ts.push(fp16(&[rows * PROBES, D]));
    ts.push(fp16(&[rows, PROBES]));
    ts.push(fp16(&[QUERIES, D]));
    ts.push(fp16(&[QUERIES, rows, PROBES]));
    ts.push(fp16(&[1, QUERIES * D]));
    ts.push(fp16(&[1]));
    ts.push(raw(b"tokenizer"));

    let mut sites_field = [0u32; 16];
    for (i, s) in sites.iter().enumerate() {
        sites_field[i] = *s as u32;
    }

    #[rustfmt::skip]
    let fields: [u32; 48] = [
        0x05E1_2A84, ts.len() as u32, cb_len as u32,
        0, 8, VOCAB as u32, VOCAB as u32, D as u32, HEADS as u32, KV_HEADS as u32,
        depth as u32, QK as u32, VH as u32, 32, HADA_N as u32, LANES as u32, 4,
        (gmask & 0xFFFF_FFFF) as u32, (gmask >> 32) as u32,
        TAPS as u32, SLOTS as u32, SUB_DIM as u32, TABLES as u32, ENGRAM_TAPS as u32,
        3, 0, 2, 2, 3, 0, 0,
        sites.len() as u32,
        sites_field[0], sites_field[1], sites_field[2], sites_field[3],
        sites_field[4], sites_field[5], sites_field[6], sites_field[7],
        sites_field[8], sites_field[9], sites_field[10], sites_field[11],
        sites_field[12], sites_field[13], sites_field[14], sites_field[15],
    ];

    let mut out = Vec::new();
    for f in fields {
        out.extend_from_slice(&f.to_le_bytes());
    }
    out.extend_from_slice(&100_000.0f32.to_le_bytes());
    assert_eq!(out.len(), HEADER);
    for _ in 0..cb_len {
        out.extend_from_slice(&0.5f32.to_le_bytes());
    }
    let mut pos = out.len() + ts.len() * REC;
    let mut offsets = Vec::with_capacity(ts.len());
    for t in &ts {
        pos = pos.div_ceil(64) * 64;
        offsets.push(pos);
        pos += t.blob.len();
    }
    for (i, t) in ts.iter().enumerate() {
        out.push(t.dtype);
        out.push(t.shape.len() as u8);
        out.extend_from_slice(&0u16.to_le_bytes());
        for k in 0..4 {
            out.extend_from_slice(&(t.shape.get(k).copied().unwrap_or(0) as u32).to_le_bytes());
        }
        out.extend_from_slice(&(offsets[i] as u64).to_le_bytes());
        out.extend_from_slice(&(t.blob.len() as u64).to_le_bytes());
        out.extend_from_slice(&0u32.to_le_bytes());
        out.extend_from_slice(&0u32.to_le_bytes());
    }
    for (i, t) in ts.iter().enumerate() {
        out.resize(offsets[i], 0);
        out.extend_from_slice(&t.blob);
    }
    out
}

fn fixture() -> Option<serde_json::Value> {
    let raw = std::fs::read_to_string(FIXTURE).ok()?;
    serde_json::from_str(&raw).ok()
}

fn u_list(v: &serde_json::Value) -> Vec<usize> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap() as usize)
        .collect()
}

#[test]
fn every_rung_shape_resolves() {
    let Some(fx) = fixture() else {
        eprintln!("skipping: no {FIXTURE}");
        return;
    };
    let rungs = fx["rungs"].as_array().unwrap();
    assert_eq!(rungs.len(), 19, "depths 2..=20");

    for r in rungs {
        let depth = r["depth"].as_u64().unwrap() as usize;
        let sites = u_list(&r["engram_sites"]);
        let globals = u_list(&r["global_layers"]);
        let gmask = globals.iter().fold(0u64, |m, g| m | (1u64 << g));

        let bytes = build_rung(depth, &sites, gmask);
        let cact = CactV3::from_bytes(bytes)
            .unwrap_or_else(|e| panic!("depth {depth}: container rejected: {e:?}"));

        assert_eq!(cact.geom.num_layers, depth);
        assert_eq!(cact.geom.engram_sites, sites, "depth {depth}: engram sites");
        assert_eq!(
            cact.geom.global_layers(),
            globals,
            "depth {depth}: global layers"
        );

        let cfg = config_from_geometry(&cact.geom)
            .unwrap_or_else(|e| panic!("depth {depth}: geometry rejected: {e:?}"));
        assert_eq!(cfg.num_layers, depth);
        assert_eq!(cfg.engram.sites, sites);

        // The canon walk is the part that would break: every per-layer slot,
        // one Engram block per surviving site, then the head.
        let layout = V3Layout::derive(&cfg, cact.records())
            .unwrap_or_else(|e| panic!("depth {depth}: canon walk failed: {e:?}"));

        // The confidence head carries one cell per block plus the embedding.
        // Checked through the directory rather than by building the head: the
        // real container stores `probes`, `query` and `proj` as Cactus-Quants
        // and the loader requires that, which is a property of the export and
        // not something a rung changes. `gain` is fp16 and its leading axis is
        // the cell count, so it answers the question without a CQ blob.
        assert!(
            layout.head_manifest.is_some(),
            "depth {depth}: no head manifest"
        );
        let gain = cact.record(layout.head_tensors[1]);
        assert_eq!(
            gain.shape[0] as usize,
            depth + 1,
            "depth {depth}: head cells must be blocks + the embedding cell"
        );
    }
    println!("all 19 rung shapes (depths 2..=20) parse, resolve and carry a right-sized head");
}

#[test]
fn the_ladder_always_keeps_both_endpoints_and_a_global_layer() {
    let Some(fx) = fixture() else { return };
    let parent = fx["parent_layers"].as_u64().unwrap() as usize;
    for r in fx["rungs"].as_array().unwrap() {
        let depth = r["depth"].as_u64().unwrap() as usize;
        let sel = u_list(&r["selected"]);
        assert_eq!(sel.len(), depth);
        assert_eq!(sel[0], 0, "depth {depth}: block 0 is always kept");
        assert_eq!(
            *sel.last().unwrap(),
            parent - 1,
            "depth {depth}: the last block is always kept"
        );
        // Block 19 carries both a global layer and an Engram site upstream, so
        // no rung is left without either. A rung that lost both would change
        // the attention and memory story, not just the depth.
        assert!(
            !u_list(&r["global_layers"]).is_empty(),
            "depth {depth}: no global-attention layer survived"
        );
        assert!(
            !u_list(&r["engram_sites"]).is_empty(),
            "depth {depth}: no Engram site survived"
        );
    }
    println!("every rung keeps both endpoints, a global layer and an Engram site");
}

#[test]
fn the_cache_shrinks_with_depth() {
    let Some(fx) = fixture() else { return };
    let mut last = 0usize;
    let mut first = 0usize;
    for r in fx["rungs"].as_array().unwrap() {
        let depth = r["depth"].as_u64().unwrap() as usize;
        let sites = u_list(&r["engram_sites"]);
        let globals = u_list(&r["global_layers"]);
        let gmask = globals.iter().fold(0u64, |m, g| m | (1u64 << g));
        let cact = CactV3::from_bytes(build_rung(depth, &sites, gmask)).unwrap();
        let cfg = config_from_geometry(&cact.geom).unwrap();

        // The cache is per-layer, so it has to fall with depth for a rung to be
        // worth loading on a constrained target at all.
        let bytes = cfg.kv_bytes(512, 4);
        assert!(
            bytes > last,
            "depth {depth}: cache {bytes} did not grow over the shallower rung's {last}"
        );
        if first == 0 {
            first = bytes;
        }
        last = bytes;
    }
    println!(
        "kv_bytes(512) scales with depth: {:.1} KB at the shallowest rung, {:.1} KB at 20",
        first as f64 / 1024.0,
        last as f64 / 1024.0
    );
    // Monotonic is the load-bearing property; the exact ratio is a function of
    // how many rungs are global, which the ladder decides, not us.
    assert!(
        last > first * 3,
        "the deepest rung's cache ({last}) should be far above the shallowest ({first})"
    );
}
